version: '3.8'

services:
  bank-processor:
    build: .
    container_name: bank-processor
    restart: unless-stopped
    volumes:
      - ./data/state:/app/state
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_RECEIVER=${EMAIL_RECEIVER}
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_FILE=${DB_FILE:-/app/state/transactions.db}
      - EXCEL_SHEET_NAME=${EXCEL_SHEET_NAME:-0}
      - EXCEL_SKIP_ROWS=${EXCEL_SKIP_ROWS:-0}
      - COL_DATE_EXCEL=${COL_DATE_EXCEL:-Fecha}
      - COL_DESC_EXCEL=${COL_DESC_EXCEL:-Descripción}
      - COL_AMOUNT_EXCEL=${COL_AMOUNT_EXCEL:-Importe}
      - COL_BANK_ID_EXCEL=${COL_BANK_ID_EXCEL}
      - TZ=Europe/Madrid
      - API_PORT=${API_PORT:-5001}
      - SIMILARITY_THRESHOLD=${SIMILARITY_THRESHOLD:-0.6} # Umbral más bajo para preguntar
      - DATE_WINDOW_DAYS=${DATE_WINDOW_DAYS:-3}
    env_file:
      - .env

  telegram-bot:
    build: ./telegram_bot
    container_name: telegram_excel_listener
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ALLOWED_USER_ID=${ALLOWED_USER_ID}
      - TZ=Europe/Madrid
      - PROCESSOR_API_URL=${PROCESSOR_API_URL:-http://bank-processor:5001/api}
    env_file:
      - .env