name: Docker Image CI & Push to GHCR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push bank-processor Image
      run: |
        IMAGE_TAG_BASE="ghcr.io/${{ github.repository_owner }}/tarjetaeroskitelegrambot/tarjeta-eroski-processor"
        docker build . --file Dockerfile --tag ${IMAGE_TAG_BASE}:latest --tag ${IMAGE_TAG_BASE}:${{ github.sha }}
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "Pushing bank-processor image to GHCR..."
          docker push ${IMAGE_TAG_BASE}:latest
          docker push ${IMAGE_TAG_BASE}:${{ github.sha }}
        else
          echo "Skipping push for PR or non-main branch."
        fi

    - name: Build and Push telegram-bot Image
      run: |
        IMAGE_TAG_BASE="ghcr.io/${{ github.repository_owner }}/tarjetaeroskitelegrambot/tarjeta-eroski-telegram-bot"
        docker build ./telegram_bot --file ./telegram_bot/Dockerfile --tag ${IMAGE_TAG_BASE}:latest --tag ${IMAGE_TAG_BASE}:${{ github.sha }}
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "Pushing telegram-bot image to GHCR..."
          docker push ${IMAGE_TAG_BASE}:latest
          docker push ${IMAGE_TAG_BASE}:${{ github.sha }}
        else
          echo "Skipping push for PR or non-main branch."
        fi
