name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build processor docker image
      run: docker build . --file Dockerfile --tag tarjeta_eroski_movements_processor:$(date +%s)
    - name: Build telegram bot docker image
      run: docker build . --file ./telegram_bot/Dockerfile --tag tarjeta_eroski_movements_processor:$(date +%s)  
